baseURL = "https://nethermead.netlify.com"
disqusShortname = ""
googleAnalytics = ""
paginate = "3"
summaryLength = "50"
theme = "touchy-hugo"
title = "Touchy Hugo | Minimal Blog Theme"
[markup.goldmark.renderer]
unsafe = true
[[menu.main]]
name = "About"
url = "about"
weight = 1
[[menu.main]]
name = "Elemetns"
url = "elements"
weight = 2
[[menu.main]]
name = "Terms & Conditions"
url = "terms-conditions"
weight = 3
[[menu.main]]
name = "Contact"
url = "contact"
weight = 4
[outputs]
home = ["HTML", "RSS"]
[params]
address = "9567 Turner Trace Apt. BC C3G8A4"
author = "Themefisher"
copyright = "Designed & Developed By [Gethugothemes](https://gethugothemes.com/)"
custom_script = ""
description = "This is meta description"
email = "info@email.com"
favicon = "images/favicon.png"
logo = "images/logo.png"
logo_width = "100px"
mobile = "+211234565523"
[params.cookies]
enable = false
expire_days = 2
[[params.plugins.css]]
attributes = "media"
link = "https://fonts.googleapis.com/css2?family=Crimson+Text&family=Raleway:wght@400;500;600&display=swap"
[[params.plugins.js]]
attributes = "defer"
link = "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/js/fontawesome.min.js"
[[params.plugins.js]]
attributes = "defer"
link = "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/js/brands.min.js"
[[params.plugins.js]]
attributes = "data-turbolinks-suppress-warning defer"
link = "plugins/turbolinks/turbolinks.js"
[[params.social]]
icon = "fab fa-facebook"
link = "#"
title = "facebook"
[[params.social]]
icon = "fab fa-twitter"
link = "#"
title = "twitter"
[[params.social]]
icon = "fab fa-instagram"
link = "#"
title = "instagram"
[[params.social]]
icon = "fab fa-github"
link = "#"
title = "github"
[[params.social]]
icon = "fab fa-linkedin"
link = "#"
title = "linkedin"
