baseURL = "https://nethermead.netlify.com"
disqusShortname = ""
googleAnalytics = ""
paginate = "3"
summaryLength = "0"
theme = "touchy-hugo"
title = "The Voyage of the Nethermead"
[markup.goldmark.renderer]
unsafe = true
[[menu.main]]
name = "CONTACT"
url = "contact"
weight = 3
[[menu.main]]
name = "ABOUT"
url = "about"
weight = 1
[outputs]
home = ["HTML", "RSS"]
[params]
address = "609 Piper Dr"
author = "Eric, Alex, Leon & Margot"
copyright = "All images copyright Eric Thomas 2021"
custom_script = ""
description = "This is meta description"
email = "ericevanthomas@gmail.com"
favicon = "images/favicon.png"
logo = "/images/nethermead-logo-cropped-resized.webp"
logo_width = "200px"
mobile = "1-206-859-3842"
[params.cookies]
enable = false
expire_days = 2
[[params.plugins.css]]
attributes = "media"
link = "https://fonts.googleapis.com/css2?family=Crimson+Text&family=Raleway:wght@400;500;600&display=swap"
[[params.plugins.js]]
attributes = "defer"
link = "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/js/fontawesome.min.js"
[[params.plugins.js]]
attributes = "defer"
link = "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/js/brands.min.js"
[[params.plugins.js]]
attributes = "data-turbolinks-suppress-warning defer"
link = "plugins/turbolinks/turbolinks.js"
[[params.social]]
icon = "fa-envelope"
link = "mailto:ericevanthomas@gmail.com"
title = "Email"
[[params.social]]
icon = "fa-brands fa-whatsapp"
link = "wa.me/12068593842"
title = "WhatsApp"
